//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.CourtSession = new HashSet<CourtSession>();
        }
    
        public int Id { get; set; }
        public int PersonRef { get; set; }
        public Nullable<byte> Rank { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<CourtSession> CourtSession { get; set; }
    }
}
