//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachement
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public int LegalDocumentRef { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
    
        public virtual LegalDocument LegalDocument { get; set; }
    }
}
