//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Court = new HashSet<Court>();
            this.LegalPersonality = new HashSet<LegalPersonality>();
            this.Municipality = new HashSet<Municipality>();
            this.Person = new HashSet<Person>();
        }
    
        public string PrefixCode { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProvinceRef { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<Court> Court { get; set; }
        public virtual ICollection<LegalPersonality> LegalPersonality { get; set; }
        public virtual ICollection<Municipality> Municipality { get; set; }
        public virtual ICollection<Person> Person { get; set; }
    }
}
