//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalDocument
    {
        public LegalDocument()
        {
            this.Attachement = new HashSet<Attachement>();
            this.Complainant = new HashSet<Complainant>();
            this.CourtSession = new HashSet<CourtSession>();
            this.Invited = new HashSet<Invited>();
            this.InvolvedPersonnel = new HashSet<InvolvedPersonnel>();
            this.InvolvedUnits = new HashSet<InvolvedUnits>();
            this.LegalDocument1 = new HashSet<LegalDocument>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
        public System.DateTime PrepareDate { get; set; }
        public string ArchiveNo { get; set; }
        public string Type { get; set; }
        public string WorkflueStatus { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int MunicipalityRef { get; set; }
        public int CourtRef { get; set; }
        public string Summary { get; set; }
        public System.DateTime AnnounceDate { get; set; }
        public string Confirmer { get; set; }
        public Nullable<int> ParentDocRef { get; set; }
        public string Reciever { get; set; }
        public Nullable<System.DateTime> IndicatorRegisterDate { get; set; }
        public System.DateTime CourtRoomDate { get; set; }
        public string AnnounceNo { get; set; }
        public Nullable<System.DateTime> AnnounceToAgentDate { get; set; }
        public int CategoryRef { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Attachement> Attachement { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Complainant> Complainant { get; set; }
        public virtual Court Court { get; set; }
        public virtual ICollection<CourtSession> CourtSession { get; set; }
        public virtual ICollection<Invited> Invited { get; set; }
        public virtual ICollection<InvolvedPersonnel> InvolvedPersonnel { get; set; }
        public virtual ICollection<InvolvedUnits> InvolvedUnits { get; set; }
        public virtual ICollection<LegalDocument> LegalDocument1 { get; set; }
        public virtual LegalDocument LegalDocument2 { get; set; }
        public virtual Municipality Municipality { get; set; }
    }
}
