//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalPersonality
    {
        public LegalPersonality()
        {
            this.Complainant = new HashSet<Complainant>();
            this.Invited = new HashSet<Invited>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProvinceRef { get; set; }
        public int CityRef { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Type { get; set; }
        public int MunicipalityRef { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Complainant> Complainant { get; set; }
        public virtual ICollection<Invited> Invited { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual Province Province { get; set; }
    }
}
