//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipality
    {
        public Municipality()
        {
            this.Complainant = new HashSet<Complainant>();
            this.Invited = new HashSet<Invited>();
            this.LegalDocument = new HashSet<LegalDocument>();
            this.LegalPersonality = new HashSet<LegalPersonality>();
            this.Person = new HashSet<Person>();
            this.Personnel = new HashSet<Personnel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProvinceRef { get; set; }
        public int CityRef { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string PostalCode { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Complainant> Complainant { get; set; }
        public virtual ICollection<Invited> Invited { get; set; }
        public virtual ICollection<LegalDocument> LegalDocument { get; set; }
        public virtual ICollection<LegalPersonality> LegalPersonality { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<Person> Person { get; set; }
        public virtual ICollection<Personnel> Personnel { get; set; }
    }
}
