//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public Personnel()
        {
            this.InvolvedPersonnel = new HashSet<InvolvedPersonnel>();
            this.PersonnelPost = new HashSet<PersonnelPost>();
        }
    
        public int Id { get; set; }
        public int PersonRef { get; set; }
        public int OfficeRef { get; set; }
    
        public virtual ICollection<InvolvedPersonnel> InvolvedPersonnel { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<PersonnelPost> PersonnelPost { get; set; }
    }
}
