//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Agent = new HashSet<Agent>();
            this.Complainant = new HashSet<Complainant>();
            this.Invited = new HashSet<Invited>();
            this.Personnel = new HashSet<Personnel>();
            this.PersonnelPost = new HashSet<PersonnelPost>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NationalCode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public int ProvinceRef { get; set; }
        public int CityRef { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public Nullable<int> OfficeRef { get; set; }
    
        public virtual ICollection<Agent> Agent { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Complainant> Complainant { get; set; }
        public virtual ICollection<Invited> Invited { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<Personnel> Personnel { get; set; }
        public virtual ICollection<PersonnelPost> PersonnelPost { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
